/**
 * Auto-generated Gallery Configuration
 * Generated by scripts/generateGalleryConfig.mjs
 */
var galleryConfig = {
  groups: [
    {
      "id": "group1",
      "audioSrc": "assets/groups/group1/group1.ogg",
      "images": [
        {
          "id": "group1-g1-img1",
          "src": "assets/groups/group1/g1-img1.jpg",
          "caption": "g1-img1.jpg"
        },
        {
          "id": "group1-g1-img2",
          "src": "assets/groups/group1/g1-img2.jpg",
          "caption": "g1-img2.jpg"
        },
        {
          "id": "group1-g1-img3",
          "src": "assets/groups/group1/g1-img3.jpg",
          "caption": "g1-img3.jpg"
        }
      ]
    },
    {
      "id": "group2",
      "audioSrc": "assets/groups/group2/group2.ogg",
      "images": [
        {
          "id": "group2-g2-img1",
          "src": "assets/groups/group2/g2-img1.jpg",
          "caption": "g2-img1.jpg"
        },
        {
          "id": "group2-g2-img2",
          "src": "assets/groups/group2/g2-img2.jpg",
          "caption": "g2-img2.jpg"
        }
      ]
    }
  ]
};
