/**
 * Auto-generated Gallery Configuration
 * Generated by scripts/generateGalleryConfig.mjs
 */
const galleryConfig = {
  groups: [
  {
    "id": "01_ambianceruepuismusique",
    "audioSrc": "assets/groups/01_ambianceruepuismusique/01_ambianceruepuismusique.ogg",
    "images": [
      {
        "id": "01_ambianceruepuismusique-g1-img1",
        "src": "assets/groups/01_ambianceruepuismusique/g1-img1.jpg",
        "caption": "g1-img1.jpg"
      },
      {
        "id": "01_ambianceruepuismusique-g1-img2",
        "src": "assets/groups/01_ambianceruepuismusique/g1-img2.jpg",
        "caption": "g1-img2.jpg"
      },
      {
        "id": "01_ambianceruepuismusique-g1-img3",
        "src": "assets/groups/01_ambianceruepuismusique/g1-img3.jpg",
        "caption": "g1-img3.jpg"
      }
    ]
  },
  {
    "id": "2_ambiancederue",
    "audioSrc": "assets/groups/2_ambiancederue/2_ambiancederue.ogg",
    "images": [
      {
        "id": "2_ambiancederue-g2-img1",
        "src": "assets/groups/2_ambiancederue/g2-img1.jpg",
        "caption": "g2-img1.jpg"
      },
      {
        "id": "2_ambiancederue-g2-img2",
        "src": "assets/groups/2_ambiancederue/g2-img2.jpg",
        "caption": "g2-img2.jpg"
      }
    ]
  }
]
};
