/**
 * Auto-generated Gallery Configuration
 * Generated by scripts/generateGalleryConfig.mjs
 */
const galleryConfig = {
  "enableSound": true,
  "ui": {
    "pageTitle": "Resonance",
    "buttonLabels": {
      "previous": "Previous",
      "next": "Next"
    },
    "messages": {
      "startPrompt": "Press Enter or Click to Start",
      "loading": "Loading..."
    }
  },
  "timing": {
    "transitionDuration": 200,
    "fullscreenControlsHideDelay": 3000,
    "longPressDuration": 800,
    "loadingOverlayFadeDuration": 500
  },
  "touch": {
    "swipeThreshold": 50,
    "tapThreshold": 10,
    "swipeVerticalTolerance": 100
  },
  "performance": {
    "maxCacheSize": 50,
    "concurrencyLimit": 6
  },
  "transitions": {
    "type": "fade",
    "duration": 200
  },
  "groups": [
    {
      "id": "01_ambianceruepuismusique",
      "audioSources": [
        "assets/groups/01_ambianceruepuismusique/01_ambianceruepuismusique.mp3",
        "assets/groups/01_ambianceruepuismusique/01_ambianceruepuismusique.ogg"
      ],
      "images": [
        {
          "id": "01_ambianceruepuismusique-000007490007",
          "src": "assets/groups/01_ambianceruepuismusique/000007490007.jpg",
          "caption": "000007490007.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-000007490023",
          "src": "assets/groups/01_ambianceruepuismusique/000007490023.jpg",
          "caption": "000007490023.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-000007490024",
          "src": "assets/groups/01_ambianceruepuismusique/000007490024.jpg",
          "caption": "000007490024.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-000007490025",
          "src": "assets/groups/01_ambianceruepuismusique/000007490025.jpg",
          "caption": "000007490025.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-000007490027",
          "src": "assets/groups/01_ambianceruepuismusique/000007490027.jpg",
          "caption": "000007490027.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_2862",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_2862.jpg",
          "caption": "DSC_2862.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_2916",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_2916.jpg",
          "caption": "DSC_2916.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_2931",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_2931.jpg",
          "caption": "DSC_2931.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_2932",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_2932.jpg",
          "caption": "DSC_2932.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_2934",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_2934.jpg",
          "caption": "DSC_2934.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_3019",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_3019.jpg",
          "caption": "DSC_3019.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_4276",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_4276.jpg",
          "caption": "DSC_4276.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_4288",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_4288.jpg",
          "caption": "DSC_4288.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_4330",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_4330.jpg",
          "caption": "DSC_4330.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_4358",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_4358.jpg",
          "caption": "DSC_4358.jpg"
        },
        {
          "id": "01_ambianceruepuismusique-DSC_4371",
          "src": "assets/groups/01_ambianceruepuismusique/DSC_4371.jpg",
          "caption": "DSC_4371.jpg"
        }
      ]
    },
    {
      "id": "08_ferme",
      "audioSources": [
        "assets/groups/08_ferme/08_ferme.mp3",
        "assets/groups/08_ferme/08_ferme.ogg"
      ],
      "images": [
        {
          "id": "08_ferme-000007490030",
          "src": "assets/groups/08_ferme/000007490030.jpg",
          "caption": "000007490030.jpg"
        },
        {
          "id": "08_ferme-000007490032",
          "src": "assets/groups/08_ferme/000007490032.jpg",
          "caption": "000007490032.jpg"
        }
      ]
    },
    {
      "id": "08_fermev2",
      "audioSources": [
        "assets/groups/08_fermev2/08_fermev2.mp3",
        "assets/groups/08_fermev2/08_fermev2.ogg"
      ],
      "images": [
        {
          "id": "08_fermev2-DSC_3126",
          "src": "assets/groups/08_fermev2/DSC_3126.jpg",
          "caption": "DSC_3126.jpg"
        },
        {
          "id": "08_fermev2-DSC_3132",
          "src": "assets/groups/08_fermev2/DSC_3132.jpg",
          "caption": "DSC_3132.jpg"
        },
        {
          "id": "08_fermev2-DSC_3141",
          "src": "assets/groups/08_fermev2/DSC_3141.jpg",
          "caption": "DSC_3141.jpg"
        },
        {
          "id": "08_fermev2-DSC_3182",
          "src": "assets/groups/08_fermev2/DSC_3182.jpg",
          "caption": "DSC_3182.jpg"
        },
        {
          "id": "08_fermev2-DSC_3210",
          "src": "assets/groups/08_fermev2/DSC_3210.jpg",
          "caption": "DSC_3210.jpg"
        }
      ]
    },
    {
      "id": "08_voitures",
      "audioSources": [
        "assets/groups/08_voitures/08_voitures.mp3",
        "assets/groups/08_voitures/08_voitures.ogg"
      ],
      "images": [
        {
          "id": "08_voitures-DSC_2941",
          "src": "assets/groups/08_voitures/DSC_2941.jpg",
          "caption": "DSC_2941.jpg"
        },
        {
          "id": "08_voitures-DSC_2947",
          "src": "assets/groups/08_voitures/DSC_2947.jpg",
          "caption": "DSC_2947.jpg"
        },
        {
          "id": "08_voitures-DSC_2949",
          "src": "assets/groups/08_voitures/DSC_2949.jpg",
          "caption": "DSC_2949.jpg"
        },
        {
          "id": "08_voitures-DSC_2951",
          "src": "assets/groups/08_voitures/DSC_2951.jpg",
          "caption": "DSC_2951.jpg"
        },
        {
          "id": "08_voitures-DSC_2986",
          "src": "assets/groups/08_voitures/DSC_2986.jpg",
          "caption": "DSC_2986.jpg"
        },
        {
          "id": "08_voitures-DSC_2989",
          "src": "assets/groups/08_voitures/DSC_2989.jpg",
          "caption": "DSC_2989.jpg"
        },
        {
          "id": "08_voitures-DSC_2990",
          "src": "assets/groups/08_voitures/DSC_2990.jpg",
          "caption": "DSC_2990.jpg"
        }
      ]
    },
    {
      "id": "09_ambianceville",
      "audioSources": [
        "assets/groups/09_ambianceville/09_ambianceville.mp3",
        "assets/groups/09_ambianceville/09_ambianceville.ogg"
      ],
      "images": [
        {
          "id": "09_ambianceville-DSC_2999",
          "src": "assets/groups/09_ambianceville/DSC_2999.jpg",
          "caption": "DSC_2999.jpg"
        },
        {
          "id": "09_ambianceville-DSC_3010",
          "src": "assets/groups/09_ambianceville/DSC_3010.jpg",
          "caption": "DSC_3010.jpg"
        },
        {
          "id": "09_ambianceville-DSC_3014",
          "src": "assets/groups/09_ambianceville/DSC_3014.jpg",
          "caption": "DSC_3014.jpg"
        },
        {
          "id": "09_ambianceville-DSC_3016",
          "src": "assets/groups/09_ambianceville/DSC_3016.jpg",
          "caption": "DSC_3016.jpg"
        },
        {
          "id": "09_ambianceville-DSC_3017",
          "src": "assets/groups/09_ambianceville/DSC_3017.jpg",
          "caption": "DSC_3017.jpg"
        }
      ]
    },
    {
      "id": "10_trajetentucktuck",
      "audioSources": [
        "assets/groups/10_trajetentucktuck/10_trajetentucktuck.mp3",
        "assets/groups/10_trajetentucktuck/10_trajetentucktuck.ogg"
      ],
      "images": [
        {
          "id": "10_trajetentucktuck-000007510033",
          "src": "assets/groups/10_trajetentucktuck/000007510033.jpg",
          "caption": "000007510033.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3493",
          "src": "assets/groups/10_trajetentucktuck/DSC_3493.jpg",
          "caption": "DSC_3493.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3535",
          "src": "assets/groups/10_trajetentucktuck/DSC_3535.jpg",
          "caption": "DSC_3535.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3537",
          "src": "assets/groups/10_trajetentucktuck/DSC_3537.jpg",
          "caption": "DSC_3537.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3539",
          "src": "assets/groups/10_trajetentucktuck/DSC_3539.jpg",
          "caption": "DSC_3539.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3550",
          "src": "assets/groups/10_trajetentucktuck/DSC_3550.jpg",
          "caption": "DSC_3550.jpg"
        },
        {
          "id": "10_trajetentucktuck-DSC_3576",
          "src": "assets/groups/10_trajetentucktuck/DSC_3576.jpg",
          "caption": "DSC_3576.jpg"
        }
      ]
    },
    {
      "id": "11_trinidad",
      "audioSources": [
        "assets/groups/11_trinidad/11_trinidad.mp3",
        "assets/groups/11_trinidad/11_trinidad.ogg"
      ],
      "images": [
        {
          "id": "11_trinidad-000007500001",
          "src": "assets/groups/11_trinidad/000007500001.jpg",
          "caption": "000007500001.jpg"
        },
        {
          "id": "11_trinidad-000007500004",
          "src": "assets/groups/11_trinidad/000007500004.jpg",
          "caption": "000007500004.jpg"
        },
        {
          "id": "11_trinidad-000007500011",
          "src": "assets/groups/11_trinidad/000007500011.jpg",
          "caption": "000007500011.jpg"
        },
        {
          "id": "11_trinidad-000007500016",
          "src": "assets/groups/11_trinidad/000007500016.jpg",
          "caption": "000007500016.jpg"
        },
        {
          "id": "11_trinidad-000007500026",
          "src": "assets/groups/11_trinidad/000007500026.jpg",
          "caption": "000007500026.jpg"
        },
        {
          "id": "11_trinidad-000007500030",
          "src": "assets/groups/11_trinidad/000007500030.jpg",
          "caption": "000007500030.jpg"
        },
        {
          "id": "11_trinidad-DSC_3620",
          "src": "assets/groups/11_trinidad/DSC_3620.jpg",
          "caption": "DSC_3620.jpg"
        },
        {
          "id": "11_trinidad-DSC_3623",
          "src": "assets/groups/11_trinidad/DSC_3623.jpg",
          "caption": "DSC_3623.jpg"
        },
        {
          "id": "11_trinidad-DSC_3628",
          "src": "assets/groups/11_trinidad/DSC_3628.jpg",
          "caption": "DSC_3628.jpg"
        },
        {
          "id": "11_trinidad-DSC_3633",
          "src": "assets/groups/11_trinidad/DSC_3633.jpg",
          "caption": "DSC_3633.jpg"
        },
        {
          "id": "11_trinidad-DSC_3647",
          "src": "assets/groups/11_trinidad/DSC_3647.jpg",
          "caption": "DSC_3647.jpg"
        },
        {
          "id": "11_trinidad-DSC_3653",
          "src": "assets/groups/11_trinidad/DSC_3653.jpg",
          "caption": "DSC_3653.jpg"
        },
        {
          "id": "11_trinidad-DSC_3676",
          "src": "assets/groups/11_trinidad/DSC_3676.jpg",
          "caption": "DSC_3676.jpg"
        },
        {
          "id": "11_trinidad-DSC_3702",
          "src": "assets/groups/11_trinidad/DSC_3702.jpg",
          "caption": "DSC_3702.jpg"
        },
        {
          "id": "11_trinidad-DSC_3726",
          "src": "assets/groups/11_trinidad/DSC_3726.jpg",
          "caption": "DSC_3726.jpg"
        },
        {
          "id": "11_trinidad-DSC_3727",
          "src": "assets/groups/11_trinidad/DSC_3727.jpg",
          "caption": "DSC_3727.jpg"
        },
        {
          "id": "11_trinidad-DSC_3730",
          "src": "assets/groups/11_trinidad/DSC_3730.jpg",
          "caption": "DSC_3730.jpg"
        },
        {
          "id": "11_trinidad-DSC_3741",
          "src": "assets/groups/11_trinidad/DSC_3741.jpg",
          "caption": "DSC_3741.jpg"
        },
        {
          "id": "11_trinidad-DSC_3783",
          "src": "assets/groups/11_trinidad/DSC_3783.jpg",
          "caption": "DSC_3783.jpg"
        },
        {
          "id": "11_trinidad-DSC_3817",
          "src": "assets/groups/11_trinidad/DSC_3817.jpg",
          "caption": "DSC_3817.jpg"
        },
        {
          "id": "11_trinidad-DSC_3834",
          "src": "assets/groups/11_trinidad/DSC_3834.jpg",
          "caption": "DSC_3834.jpg"
        },
        {
          "id": "11_trinidad-DSC_3837",
          "src": "assets/groups/11_trinidad/DSC_3837.jpg",
          "caption": "DSC_3837.jpg"
        },
        {
          "id": "11_trinidad-DSC_3839",
          "src": "assets/groups/11_trinidad/DSC_3839.jpg",
          "caption": "DSC_3839.jpg"
        },
        {
          "id": "11_trinidad-DSC_3955",
          "src": "assets/groups/11_trinidad/DSC_3955.jpg",
          "caption": "DSC_3955.jpg"
        },
        {
          "id": "11_trinidad-DSC_3999",
          "src": "assets/groups/11_trinidad/DSC_3999.jpg",
          "caption": "DSC_3999.jpg"
        },
        {
          "id": "11_trinidad-DSC_4002",
          "src": "assets/groups/11_trinidad/DSC_4002.jpg",
          "caption": "DSC_4002.jpg"
        },
        {
          "id": "11_trinidad-DSC_4004",
          "src": "assets/groups/11_trinidad/DSC_4004.jpg",
          "caption": "DSC_4004.jpg"
        },
        {
          "id": "11_trinidad-DSC_4014",
          "src": "assets/groups/11_trinidad/DSC_4014.jpg",
          "caption": "DSC_4014.jpg"
        },
        {
          "id": "11_trinidad-DSC_4020",
          "src": "assets/groups/11_trinidad/DSC_4020.jpg",
          "caption": "DSC_4020.jpg"
        },
        {
          "id": "11_trinidad-DSC_4082",
          "src": "assets/groups/11_trinidad/DSC_4082.jpg",
          "caption": "DSC_4082.jpg"
        },
        {
          "id": "11_trinidad-DSC_4092",
          "src": "assets/groups/11_trinidad/DSC_4092.jpg",
          "caption": "DSC_4092.jpg"
        }
      ]
    },
    {
      "id": "12_trinidadgens",
      "audioSources": [
        "assets/groups/12_trinidadgens/12_trinidadgens.mp3",
        "assets/groups/12_trinidadgens/12_trinidadgens.ogg"
      ],
      "images": [
        {
          "id": "12_trinidadgens-000007500015",
          "src": "assets/groups/12_trinidadgens/000007500015.jpg",
          "caption": "000007500015.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_3612",
          "src": "assets/groups/12_trinidadgens/DSC_3612.jpg",
          "caption": "DSC_3612.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_3927",
          "src": "assets/groups/12_trinidadgens/DSC_3927.jpg",
          "caption": "DSC_3927.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_3929",
          "src": "assets/groups/12_trinidadgens/DSC_3929.jpg",
          "caption": "DSC_3929.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4012",
          "src": "assets/groups/12_trinidadgens/DSC_4012.jpg",
          "caption": "DSC_4012.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4065",
          "src": "assets/groups/12_trinidadgens/DSC_4065.jpg",
          "caption": "DSC_4065.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4074",
          "src": "assets/groups/12_trinidadgens/DSC_4074.jpg",
          "caption": "DSC_4074.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4075",
          "src": "assets/groups/12_trinidadgens/DSC_4075.jpg",
          "caption": "DSC_4075.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4078",
          "src": "assets/groups/12_trinidadgens/DSC_4078.jpg",
          "caption": "DSC_4078.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4079",
          "src": "assets/groups/12_trinidadgens/DSC_4079.jpg",
          "caption": "DSC_4079.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4081",
          "src": "assets/groups/12_trinidadgens/DSC_4081.jpg",
          "caption": "DSC_4081.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4102",
          "src": "assets/groups/12_trinidadgens/DSC_4102.jpg",
          "caption": "DSC_4102.jpg"
        },
        {
          "id": "12_trinidadgens-DSC_4121",
          "src": "assets/groups/12_trinidadgens/DSC_4121.jpg",
          "caption": "DSC_4121.jpg"
        }
      ]
    },
    {
      "id": "2_ambiancederue",
      "audioSources": [
        "assets/groups/2_ambiancederue/2_ambiancederue.mp3",
        "assets/groups/2_ambiancederue/2_ambiancederue.ogg"
      ],
      "images": [
        {
          "id": "2_ambiancederue-DSC_2956",
          "src": "assets/groups/2_ambiancederue/DSC_2956.jpg",
          "caption": "DSC_2956.jpg"
        },
        {
          "id": "2_ambiancederue-DSC_2959",
          "src": "assets/groups/2_ambiancederue/DSC_2959.jpg",
          "caption": "DSC_2959.jpg"
        },
        {
          "id": "2_ambiancederue-DSC_2966",
          "src": "assets/groups/2_ambiancederue/DSC_2966.jpg",
          "caption": "DSC_2966.jpg"
        },
        {
          "id": "2_ambiancederue-DSC_2991",
          "src": "assets/groups/2_ambiancederue/DSC_2991.jpg",
          "caption": "DSC_2991.jpg"
        },
        {
          "id": "2_ambiancederue-DSC_2993",
          "src": "assets/groups/2_ambiancederue/DSC_2993.jpg",
          "caption": "DSC_2993.jpg"
        }
      ]
    },
    {
      "id": "3_jungle",
      "audioSources": [
        "assets/groups/3_jungle/3_jungle.mp3",
        "assets/groups/3_jungle/3_jungle.ogg"
      ],
      "images": [
        {
          "id": "3_jungle-DSC_3046",
          "src": "assets/groups/3_jungle/DSC_3046.jpg",
          "caption": "DSC_3046.jpg"
        },
        {
          "id": "3_jungle-DSC_3055",
          "src": "assets/groups/3_jungle/DSC_3055.jpg",
          "caption": "DSC_3055.jpg"
        }
      ]
    },
    {
      "id": "4_mer",
      "audioSources": [
        "assets/groups/4_mer/4_mer.mp3",
        "assets/groups/4_mer/4_mer.ogg"
      ],
      "images": [
        {
          "id": "4_mer-000007510003",
          "src": "assets/groups/4_mer/000007510003.jpg",
          "caption": "000007510003.jpg"
        },
        {
          "id": "4_mer-000007510005",
          "src": "assets/groups/4_mer/000007510005.jpg",
          "caption": "000007510005.jpg"
        },
        {
          "id": "4_mer-000007510018",
          "src": "assets/groups/4_mer/000007510018.jpg",
          "caption": "000007510018.jpg"
        },
        {
          "id": "4_mer-DSC_3286",
          "src": "assets/groups/4_mer/DSC_3286.jpg",
          "caption": "DSC_3286.jpg"
        },
        {
          "id": "4_mer-DSC_3294",
          "src": "assets/groups/4_mer/DSC_3294.jpg",
          "caption": "DSC_3294.jpg"
        },
        {
          "id": "4_mer-DSC_3312",
          "src": "assets/groups/4_mer/DSC_3312.jpg",
          "caption": "DSC_3312.jpg"
        },
        {
          "id": "4_mer-DSC_3346",
          "src": "assets/groups/4_mer/DSC_3346.jpg",
          "caption": "DSC_3346.jpg"
        },
        {
          "id": "4_mer-DSC_3361",
          "src": "assets/groups/4_mer/DSC_3361.jpg",
          "caption": "DSC_3361.jpg"
        },
        {
          "id": "4_mer-DSC_3363",
          "src": "assets/groups/4_mer/DSC_3363.jpg",
          "caption": "DSC_3363.jpg"
        },
        {
          "id": "4_mer-DSC_3389",
          "src": "assets/groups/4_mer/DSC_3389.jpg",
          "caption": "DSC_3389.jpg"
        },
        {
          "id": "4_mer-DSC_4178",
          "src": "assets/groups/4_mer/DSC_4178.jpg",
          "caption": "DSC_4178.jpg"
        },
        {
          "id": "4_mer-DSC_4192",
          "src": "assets/groups/4_mer/DSC_4192.jpg",
          "caption": "DSC_4192.jpg"
        },
        {
          "id": "4_mer-DSC_4221",
          "src": "assets/groups/4_mer/DSC_4221.jpg",
          "caption": "DSC_4221.jpg"
        }
      ]
    },
    {
      "id": "5_ambiancederuepinardelrio",
      "audioSources": [
        "assets/groups/5_ambiancederuepinardelrio/5_ambiancederuepinardelrio.mp3",
        "assets/groups/5_ambiancederuepinardelrio/5_ambiancederuepinardelrio.ogg"
      ],
      "images": [
        {
          "id": "5_ambiancederuepinardelrio-DSC_3419",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3419.jpg",
          "caption": "DSC_3419.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3430",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3430.jpg",
          "caption": "DSC_3430.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3431",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3431.jpg",
          "caption": "DSC_3431.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3443",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3443.jpg",
          "caption": "DSC_3443.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3457",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3457.jpg",
          "caption": "DSC_3457.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3458",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3458.jpg",
          "caption": "DSC_3458.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3466",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3466.jpg",
          "caption": "DSC_3466.jpg"
        },
        {
          "id": "5_ambiancederuepinardelrio-DSC_3484",
          "src": "assets/groups/5_ambiancederuepinardelrio/DSC_3484.jpg",
          "caption": "DSC_3484.jpg"
        }
      ]
    },
    {
      "id": "6_cascade",
      "audioSources": [
        "assets/groups/6_cascade/6_cascade.mp3",
        "assets/groups/6_cascade/6_cascade.ogg"
      ],
      "images": [
        {
          "id": "6_cascade-DSC_3074",
          "src": "assets/groups/6_cascade/DSC_3074.jpg",
          "caption": "DSC_3074.jpg"
        },
        {
          "id": "6_cascade-DSC_3080",
          "src": "assets/groups/6_cascade/DSC_3080.jpg",
          "caption": "DSC_3080.jpg"
        }
      ]
    }
  ]
};
