import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ASSETS_DIR = path.join(__dirname, '../assets/groups');
const OUTPUT_FILE = path.join(__dirname, '../js/generatedConfig.js');
const SETTINGS_FILE = path.join(__dirname, '../settings.json');

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp'];
const AUDIO_EXTENSIONS = ['.mp3', '.ogg', '.wav'];

// Default settings structure
const DEFAULT_SETTINGS = {
    enableSound: true,
    ui: {
        pageTitle: 'Resonance',
        buttonLabels: {
            previous: 'Previous',
            next: 'Next'
        },
        messages: {
            startPrompt: 'Press Enter or Click to Start',
            loading: 'Loading...'
        }
    },
    timing: {
        transitionDuration: 200,
        fullscreenControlsHideDelay: 3000,
        longPressDuration: 800,
        loadingOverlayFadeDuration: 500
    },
    touch: {
        swipeThreshold: 50,
        tapThreshold: 10,
        swipeVerticalTolerance: 100
    },
    performance: {
        maxCacheSize: 50,
        concurrencyLimit: 6
    },
    transitions: {
        type: 'fade',
        duration: 200
    }
};

/**
 * Deep merge two objects, with userSettings taking precedence
 */
function mergeSettings(defaults, userSettings) {
    const result = { ...defaults };

    for (const key in userSettings) {
        if (userSettings[key] !== null && typeof userSettings[key] === 'object' && !Array.isArray(userSettings[key])) {
            result[key] = mergeSettings(defaults[key] || {}, userSettings[key]);
        } else {
            result[key] = userSettings[key];
        }
    }

    return result;
}

function readSettings() {
    // Read settings.json if it exists, otherwise use defaults
    if (fs.existsSync(SETTINGS_FILE)) {
        try {
            const settingsContent = fs.readFileSync(SETTINGS_FILE, 'utf-8');
            const userSettings = JSON.parse(settingsContent);
            console.log('Settings loaded from settings.json');

            // Merge user settings with defaults
            const mergedSettings = mergeSettings(DEFAULT_SETTINGS, userSettings);
            return mergedSettings;
        } catch (error) {
            console.warn('Error reading settings.json, using defaults:', error.message);
            return DEFAULT_SETTINGS;
        }
    } else {
        console.log('No settings.json found, using default settings');
        return DEFAULT_SETTINGS;
    }
}

function generateConfig() {
    console.log('Scanning assets directory:', ASSETS_DIR);

    if (!fs.existsSync(ASSETS_DIR)) {
        console.error('Assets directory not found!');
        return;
    }

    const settings = readSettings();
    const groups = [];
    const groupFolders = fs.readdirSync(ASSETS_DIR).sort();

    for (const folder of groupFolders) {
        const folderPath = path.join(ASSETS_DIR, folder);
        if (!fs.statSync(folderPath).isDirectory()) continue;

        console.log(`Processing group: ${folder}`);

        const files = fs.readdirSync(folderPath).sort();
        const images = [];
        const audioSources = [];

        for (const file of files) {
            const ext = path.extname(file).toLowerCase();
            const filePath = `assets/groups/${folder}/${file}`;

            if (IMAGE_EXTENSIONS.includes(ext)) {
                images.push({
                    id: `${folder}-${path.basename(file, ext)}`,
                    src: filePath,
                    caption: file // Use filename as caption for now
                });
            } else if (AUDIO_EXTENSIONS.includes(ext)) {
                audioSources.push(filePath);
            }
        }

        if (images.length > 0) {
            groups.push({
                id: folder,
                audioSources: audioSources,
                images: images
            });
        }
    }

    const configContent = `/**
 * Auto-generated Gallery Configuration
 * Generated by scripts/generateGalleryConfig.mjs
 */
const galleryConfig = ${JSON.stringify({ ...settings, groups }, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, configContent);
    console.log(`Configuration generated at: ${OUTPUT_FILE}`);
    console.log(`Settings applied:`);
    console.log(`  - Sound enabled: ${settings.enableSound}`);
    console.log(`  - Page title: ${settings.ui.pageTitle}`);
    console.log(`  - Transition duration: ${settings.timing.transitionDuration}ms`);
    console.log(`  - Transition type: ${settings.transitions.type}`);
}

generateConfig();
