import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ASSETS_DIR = path.join(__dirname, '../assets/groups');
const OUTPUT_FILE = path.join(__dirname, '../js/generatedConfig.js');

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp'];
const AUDIO_EXTENSIONS = ['.mp3', '.ogg', '.wav'];

function generateConfig() {
    console.log('Scanning assets directory:', ASSETS_DIR);

    if (!fs.existsSync(ASSETS_DIR)) {
        console.error('Assets directory not found!');
        return;
    }

    const groups = [];
    const groupFolders = fs.readdirSync(ASSETS_DIR).sort();

    for (const folder of groupFolders) {
        const folderPath = path.join(ASSETS_DIR, folder);
        if (!fs.statSync(folderPath).isDirectory()) continue;

        console.log(`Processing group: ${folder}`);

        const files = fs.readdirSync(folderPath).sort();
        const images = [];
        let audioSrc = null;

        for (const file of files) {
            const ext = path.extname(file).toLowerCase();
            const filePath = `assets/groups/${folder}/${file}`;

            if (IMAGE_EXTENSIONS.includes(ext)) {
                images.push({
                    id: `${folder}-${path.basename(file, ext)}`,
                    src: filePath,
                    caption: file // Use filename as caption for now
                });
            } else if (AUDIO_EXTENSIONS.includes(ext)) {
                if (!audioSrc) {
                    audioSrc = filePath;
                }
            }
        }

        if (images.length > 0) {
            groups.push({
                id: folder,
                audioSrc: audioSrc,
                images: images
            });
        }
    }

    const configContent = `/**
 * Auto-generated Gallery Configuration
 * Generated by scripts/generateGalleryConfig.mjs
 */
const galleryConfig = {
  groups: ${JSON.stringify(groups, null, 2)}
};
`;

    fs.writeFileSync(OUTPUT_FILE, configContent);
    console.log(`Configuration generated at: ${OUTPUT_FILE}`);
}

generateConfig();
