# agent-ci-pipeline.yaml
# Declarative CI/CD-like pipeline for AI agents

version: 1

stages:
  - name: "specification"
    description: "Clarify business value, users, and scope."
    agents:
      - id: "product-owner-agent"
        required: true

  - name: "architecture"
    description: "Shape solution design and technical approach."
    agents:
      - id: "architect-agent"
        required: true

  - name: "experience-design"
    description: "Design interactions and look & feel."
    agents:
      - id: "ux-agent"
        required: false
      - id: "ui-designer-agent"
        required: false

  - name: "implementation"
    description: "Implement feature or refactor safely."
    agents:
      - id: "senior-dev-agent"
        required: true

  - name: "code-review"
    description: "Review code quality and best practices."
    agents:
      - id: "code-review-agent"
        required: true

  - name: "testing"
    description: "Comprehensive testing at all levels."
    agents:
      - id: "unit-test-agent"
        required: true
      - id: "integration-test-agent"
        required: true
      - id: "test-agent"
        required: true

  - name: "quality-gates"
    description: "Validate quality, risk, and behavior."
    agents:
      - id: "security-agent"
        required: true
      - id: "performance-agent"
        required: true
      - id: "accessibility-agent"
        required: true

  - name: "documentation"
    description: "Update docs, release notes, and onboarding material."
    agents:
      - id: "docs-agent"
        required: true

  - name: "release-preparation"
    description: "Version management and release notes."
    agents:
      - id: "release-manager-agent"
        required: false

  - name: "deployment-planning"
    description: "Deployment orchestration and CI/CD configs."
    agents:
      - id: "deployment-agent"
        required: false

  - name: "monitoring-setup"
    description: "Observability and error tracking."
    agents:
      - id: "monitoring-agent"
        required: false

defaults:
  parallel_quality_gates: true   # test/security/perf/a11y can conceptually run in parallel
  parallel_testing: true         # unit/integration/e2e can run in parallel where possible
  fail_fast: true                # stop pipeline if a required agent surfaces blocking issues

